export DATASOURCE_RC=.datasource.rc
export DATASOURCE_ROOT=${DATASOURCE_ROOT:-.}
export DATASOURCE_PATH=${DATASOURCE_ROOT}/datasources
export DATASOURCE_SCHEMA_PATH=${DATASOURCE_ROOT}/schema
export DATASOURCE_ENABLED=${DATASOURCE_PATH}/enabled.input
